 -- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."AssignmentCache"
(
    assignment_id text COLLATE pg_catalog."default" NOT NULL,
    bus_route text COLLATE pg_catalog."default" NOT NULL,
    bus_type text COLLATE pg_catalog."default" NOT NULL,
    date_assigned timestamp(3) without time zone NOT NULL,
    trip_fuel_expense numeric(20, 4) NOT NULL,
    trip_revenue numeric(20, 4) NOT NULL,
    is_revenue_recorded boolean NOT NULL DEFAULT false,
    assignment_type text COLLATE pg_catalog."default" NOT NULL,
    last_updated timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_expense_recorded boolean NOT NULL DEFAULT false,
    assignment_value numeric(20, 4) NOT NULL,
    bus_plate_number text COLLATE pg_catalog."default" NOT NULL,
    payment_method text COLLATE pg_catalog."default" NOT NULL,
    conductor_id text COLLATE pg_catalog."default" NOT NULL,
    driver_id text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "AssignmentCache_pkey" PRIMARY KEY (assignment_id)
);

CREATE TABLE IF NOT EXISTS public."AuditLog"
(
    log_id text COLLATE pg_catalog."default" NOT NULL,
    action text COLLATE pg_catalog."default" NOT NULL,
    table_affected text COLLATE pg_catalog."default" NOT NULL,
    record_id text COLLATE pg_catalog."default" NOT NULL,
    performed_by text COLLATE pg_catalog."default" NOT NULL,
    "timestamp" timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address text COLLATE pg_catalog."default",
    details jsonb,
    CONSTRAINT "AuditLog_pkey" PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public."EmployeeCache"
(
    employee_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    job_title text COLLATE pg_catalog."default" NOT NULL,
    last_updated timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "EmployeeCache_pkey" PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS public."ExpenseRecord"
(
    expense_id text COLLATE pg_catalog."default" NOT NULL,
    assignment_id text COLLATE pg_catalog."default",
    total_amount numeric(20, 4) NOT NULL,
    receipt_id text COLLATE pg_catalog."default",
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    created_by text COLLATE pg_catalog."default" NOT NULL,
    expense_date timestamp(3) without time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    category_id text COLLATE pg_catalog."default" NOT NULL,
    source_id text COLLATE pg_catalog."default",
    payment_method_id text COLLATE pg_catalog."default" NOT NULL,
    bus_trip_id text COLLATE pg_catalog."default",
    CONSTRAINT "ExpenseRecord_pkey" PRIMARY KEY (expense_id)
);

CREATE TABLE IF NOT EXISTS public."GlobalCategory"
(
    category_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    applicable_modules text[] COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    CONSTRAINT "GlobalCategory_pkey" PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public."GlobalItemUnit"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    applicable_modules text[] COLLATE pg_catalog."default",
    CONSTRAINT "GlobalItemUnit_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."GlobalPaymentMethod"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    applicable_modules text[] COLLATE pg_catalog."default",
    CONSTRAINT "GlobalPaymentMethod_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."GlobalPaymentStatus"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    applicable_modules text[] COLLATE pg_catalog."default",
    CONSTRAINT "GlobalPaymentStatus_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."GlobalReimbursementStatus"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    applicable_modules text[] COLLATE pg_catalog."default",
    CONSTRAINT "GlobalReimbursementStatus_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."GlobalSource"
(
    source_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    applicable_modules text[] COLLATE pg_catalog."default",
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    CONSTRAINT "GlobalSource_pkey" PRIMARY KEY (source_id)
);

CREATE TABLE IF NOT EXISTS public."GlobalTerms"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    applicable_modules text[] COLLATE pg_catalog."default",
    CONSTRAINT "GlobalTerms_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Item"
(
    item_id text COLLATE pg_catalog."default" NOT NULL,
    item_name text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    is_deleted boolean NOT NULL DEFAULT false,
    category_id text COLLATE pg_catalog."default" NOT NULL,
    unit_id text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Item_pkey" PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public."ItemTransaction"
(
    transaction_id text COLLATE pg_catalog."default" NOT NULL,
    item_id text COLLATE pg_catalog."default" NOT NULL,
    receipt_id text COLLATE pg_catalog."default",
    quantity numeric(10, 2) NOT NULL,
    unit_price numeric(20, 4) NOT NULL,
    transaction_date timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT "ItemTransaction_pkey" PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public."PayrollConfiguration"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    company_id text COLLATE pg_catalog."default" NOT NULL,
    default_work_days integer NOT NULL DEFAULT 22,
    weekend_work_allowed boolean NOT NULL DEFAULT false,
    holiday_work_rate numeric(5, 2) NOT NULL DEFAULT 1.5,
    overtime_rate numeric(5, 2) NOT NULL DEFAULT 1.25,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PayrollConfiguration_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."PayrollFrequencyConfig"
(
    id text COLLATE pg_catalog."default" NOT NULL,
    employee_number text COLLATE pg_catalog."default" NOT NULL,
    payroll_period text COLLATE pg_catalog."default" NOT NULL,
    effective_date timestamp(3) without time zone NOT NULL,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone NOT NULL,
    CONSTRAINT "PayrollFrequencyConfig_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."PayrollRecord"
(
    payroll_id text COLLATE pg_catalog."default" NOT NULL,
    employee_number text COLLATE pg_catalog."default" NOT NULL,
    employee_name text COLLATE pg_catalog."default" NOT NULL,
    first_name text COLLATE pg_catalog."default" NOT NULL,
    middle_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default" NOT NULL,
    suffix text COLLATE pg_catalog."default",
    employee_status text COLLATE pg_catalog."default" NOT NULL,
    hire_date timestamp(3) without time zone NOT NULL,
    termination_date timestamp(3) without time zone,
    job_title text COLLATE pg_catalog."default" NOT NULL,
    department text COLLATE pg_catalog."default" NOT NULL,
    payroll_period text COLLATE pg_catalog."default" NOT NULL,
    payroll_start_date timestamp(3) without time zone NOT NULL,
    payroll_end_date timestamp(3) without time zone NOT NULL,
    basic_rate numeric(20, 4) NOT NULL,
    days_worked integer NOT NULL DEFAULT 0,
    basic_pay numeric(20, 4) NOT NULL DEFAULT 0,
    overtime_regular numeric(20, 4) NOT NULL DEFAULT 0,
    overtime_holiday numeric(20, 4) NOT NULL DEFAULT 0,
    service_incentive_leave numeric(20, 4) NOT NULL DEFAULT 0,
    holiday_pay numeric(20, 4) NOT NULL DEFAULT 0,
    thirteenth_month_pay numeric(20, 4) NOT NULL DEFAULT 0,
    revenue_benefit numeric(20, 4) NOT NULL DEFAULT 0,
    safety_benefit numeric(20, 4) NOT NULL DEFAULT 0,
    additional_benefits numeric(20, 4) NOT NULL DEFAULT 0,
    sss_deduction numeric(20, 4) NOT NULL DEFAULT 0,
    philhealth_deduction numeric(20, 4) NOT NULL DEFAULT 0,
    pag_ibig_deduction numeric(20, 4) NOT NULL DEFAULT 0,
    cash_advance numeric(20, 4) NOT NULL DEFAULT 0,
    damage_shortage numeric(20, 4) NOT NULL DEFAULT 0,
    other_deductions numeric(20, 4) NOT NULL DEFAULT 0,
    gross_total_earnings numeric(20, 4) NOT NULL DEFAULT 0,
    total_deductions numeric(20, 4) NOT NULL DEFAULT 0,
    net_pay numeric(20, 4) NOT NULL DEFAULT 0,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pending'::text,
    date_released timestamp(3) without time zone,
    created_by text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by text COLLATE pg_catalog."default",
    updated_at timestamp(3) without time zone,
    is_deleted boolean NOT NULL DEFAULT false,
    calculation_notes text COLLATE pg_catalog."default",
    deleted_at timestamp(3) without time zone,
    deleted_by text COLLATE pg_catalog."default",
    hr_data_snapshot jsonb,
    processed_benefits jsonb,
    processed_deductions jsonb,
    CONSTRAINT "PayrollRecord_pkey" PRIMARY KEY (payroll_id)
);

CREATE TABLE IF NOT EXISTS public."Receipt"
(
    receipt_id text COLLATE pg_catalog."default" NOT NULL,
    supplier text COLLATE pg_catalog."default" NOT NULL,
    vat_reg_tin text COLLATE pg_catalog."default",
    date_paid timestamp(3) without time zone,
    total_amount numeric(20, 4) NOT NULL,
    vat_amount numeric(20, 4),
    total_amount_due numeric(20, 4) NOT NULL,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    created_by text COLLATE pg_catalog."default" NOT NULL,
    transaction_date timestamp(3) without time zone NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamp(3) without time zone,
    deleted_by text COLLATE pg_catalog."default",
    deletion_reason text COLLATE pg_catalog."default",
    ocr_confidence double precision,
    ocr_file_path text COLLATE pg_catalog."default",
    remarks text COLLATE pg_catalog."default",
    storage_size_bytes bigint,
    updated_by text COLLATE pg_catalog."default",
    is_expense_recorded boolean NOT NULL DEFAULT false,
    category_id text COLLATE pg_catalog."default" NOT NULL,
    source_id text COLLATE pg_catalog."default",
    payment_status_id text COLLATE pg_catalog."default" NOT NULL,
    terms_id text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Receipt_pkey" PRIMARY KEY (receipt_id)
);

CREATE TABLE IF NOT EXISTS public."ReceiptExport"
(
    export_id text COLLATE pg_catalog."default" NOT NULL,
    receipt_id text COLLATE pg_catalog."default" NOT NULL,
    format "ExportFormat" NOT NULL,
    exported_by text COLLATE pg_catalog."default" NOT NULL,
    exported_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    filters_used jsonb,
    file_path text COLLATE pg_catalog."default",
    CONSTRAINT "ReceiptExport_pkey" PRIMARY KEY (export_id)
);

CREATE TABLE IF NOT EXISTS public."ReceiptItem"
(
    receipt_item_id text COLLATE pg_catalog."default" NOT NULL,
    receipt_id text COLLATE pg_catalog."default" NOT NULL,
    quantity numeric(10, 2) NOT NULL,
    unit_price numeric(20, 4) NOT NULL,
    total_price numeric(20, 4) NOT NULL,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    created_by text COLLATE pg_catalog."default" NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    ocr_confidence double precision,
    updated_by text COLLATE pg_catalog."default",
    item_id text COLLATE pg_catalog."default" NOT NULL,
    is_inventory_processed boolean NOT NULL DEFAULT false,
    CONSTRAINT "ReceiptItem_pkey" PRIMARY KEY (receipt_item_id)
);

CREATE TABLE IF NOT EXISTS public."ReceiptKeyword"
(
    keyword_id text COLLATE pg_catalog."default" NOT NULL,
    receipt_id text COLLATE pg_catalog."default" NOT NULL,
    keyword text COLLATE pg_catalog."default" NOT NULL,
    source text COLLATE pg_catalog."default" NOT NULL,
    confidence double precision,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ReceiptKeyword_pkey" PRIMARY KEY (keyword_id)
);

CREATE TABLE IF NOT EXISTS public."ReceiptOCRField"
(
    field_id text COLLATE pg_catalog."default" NOT NULL,
    receipt_id text COLLATE pg_catalog."default" NOT NULL,
    field_name text COLLATE pg_catalog."default" NOT NULL,
    extracted_value text COLLATE pg_catalog."default" NOT NULL,
    confidence_score double precision NOT NULL,
    is_verified boolean NOT NULL DEFAULT false,
    verified_by text COLLATE pg_catalog."default",
    verified_at timestamp(3) without time zone,
    original_image_coords jsonb,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    CONSTRAINT "ReceiptOCRField_pkey" PRIMARY KEY (field_id)
);

CREATE TABLE IF NOT EXISTS public."ReceiptStorageConfig"
(
    config_id text COLLATE pg_catalog."default" NOT NULL,
    auto_archive_months integer NOT NULL DEFAULT 6,
    last_cleanup timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by text COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ReceiptStorageConfig_pkey" PRIMARY KEY (config_id)
);

CREATE TABLE IF NOT EXISTS public."ReceiptStorageMetrics"
(
    metric_id text COLLATE pg_catalog."default" NOT NULL,
    total_receipts integer NOT NULL DEFAULT 0,
    storage_used_bytes bigint NOT NULL DEFAULT 0,
    last_updated timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by text COLLATE pg_catalog."default" NOT NULL,
    updated_by text COLLATE pg_catalog."default",
    CONSTRAINT "ReceiptStorageMetrics_pkey" PRIMARY KEY (metric_id)
);

CREATE TABLE IF NOT EXISTS public."Reimbursement"
(
    reimbursement_id text COLLATE pg_catalog."default" NOT NULL,
    expense_id text COLLATE pg_catalog."default" NOT NULL,
    employee_id text COLLATE pg_catalog."default" NOT NULL,
    employee_name text COLLATE pg_catalog."default" NOT NULL,
    job_title text COLLATE pg_catalog."default",
    amount numeric(20, 4) NOT NULL,
    requested_date timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_by text COLLATE pg_catalog."default",
    approved_date timestamp(3) without time zone,
    rejection_reason text COLLATE pg_catalog."default",
    paid_by text COLLATE pg_catalog."default",
    paid_date timestamp(3) without time zone,
    payment_reference text COLLATE pg_catalog."default",
    payment_method text COLLATE pg_catalog."default",
    created_by text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by text COLLATE pg_catalog."default",
    updated_at timestamp(3) without time zone,
    is_deleted boolean NOT NULL DEFAULT false,
    cancelled_by text COLLATE pg_catalog."default",
    cancelled_date timestamp(3) without time zone,
    status_id text COLLATE pg_catalog."default" NOT NULL,
    remarks text COLLATE pg_catalog."default",
    CONSTRAINT "Reimbursement_pkey" PRIMARY KEY (reimbursement_id)
);

CREATE TABLE IF NOT EXISTS public."RevenueRecord"
(
    revenue_id text COLLATE pg_catalog."default" NOT NULL,
    assignment_id text COLLATE pg_catalog."default",
    total_amount numeric(20, 4) NOT NULL,
    created_by text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(3) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp(3) without time zone,
    is_deleted boolean NOT NULL DEFAULT false,
    collection_date timestamp(3) without time zone NOT NULL,
    category_id text COLLATE pg_catalog."default" NOT NULL,
    source_id text COLLATE pg_catalog."default",
    bus_trip_id text COLLATE pg_catalog."default",
    CONSTRAINT "RevenueRecord_pkey" PRIMARY KEY (revenue_id)
);

CREATE TABLE IF NOT EXISTS public."Sequence"
(
    name text COLLATE pg_catalog."default" NOT NULL,
    value integer NOT NULL DEFAULT 1,
    CONSTRAINT "Sequence_pkey" PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS public._prisma_migrations
(
    id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    checksum character varying(64) COLLATE pg_catalog."default" NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    logs text COLLATE pg_catalog."default",
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    applied_steps_count integer NOT NULL DEFAULT 0,
    CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."ExpenseRecord"
    ADD CONSTRAINT "ExpenseRecord_category_id_fkey" FOREIGN KEY (category_id)
    REFERENCES public."GlobalCategory" (category_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."ExpenseRecord"
    ADD CONSTRAINT "ExpenseRecord_payment_method_id_fkey" FOREIGN KEY (payment_method_id)
    REFERENCES public."GlobalPaymentMethod" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."ExpenseRecord"
    ADD CONSTRAINT "ExpenseRecord_receipt_id_fkey" FOREIGN KEY (receipt_id)
    REFERENCES public."Receipt" (receipt_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "ExpenseRecord_receipt_id_key"
    ON public."ExpenseRecord"(receipt_id);


ALTER TABLE IF EXISTS public."ExpenseRecord"
    ADD CONSTRAINT "ExpenseRecord_source_id_fkey" FOREIGN KEY (source_id)
    REFERENCES public."GlobalSource" (source_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."Item"
    ADD CONSTRAINT "Item_category_id_fkey" FOREIGN KEY (category_id)
    REFERENCES public."GlobalCategory" (category_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Item"
    ADD CONSTRAINT "Item_unit_id_fkey" FOREIGN KEY (unit_id)
    REFERENCES public."GlobalItemUnit" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."ItemTransaction"
    ADD CONSTRAINT "ItemTransaction_item_id_fkey" FOREIGN KEY (item_id)
    REFERENCES public."Item" (item_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."ItemTransaction"
    ADD CONSTRAINT "ItemTransaction_receipt_id_fkey" FOREIGN KEY (receipt_id)
    REFERENCES public."Receipt" (receipt_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."Receipt"
    ADD CONSTRAINT "Receipt_category_id_fkey" FOREIGN KEY (category_id)
    REFERENCES public."GlobalCategory" (category_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Receipt"
    ADD CONSTRAINT "Receipt_payment_status_id_fkey" FOREIGN KEY (payment_status_id)
    REFERENCES public."GlobalPaymentStatus" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Receipt"
    ADD CONSTRAINT "Receipt_source_id_fkey" FOREIGN KEY (source_id)
    REFERENCES public."GlobalSource" (source_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public."Receipt"
    ADD CONSTRAINT "Receipt_terms_id_fkey" FOREIGN KEY (terms_id)
    REFERENCES public."GlobalTerms" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."ReceiptExport"
    ADD CONSTRAINT "ReceiptExport_receipt_id_fkey" FOREIGN KEY (receipt_id)
    REFERENCES public."Receipt" (receipt_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."ReceiptItem"
    ADD CONSTRAINT "ReceiptItem_item_id_fkey" FOREIGN KEY (item_id)
    REFERENCES public."Item" (item_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."ReceiptItem"
    ADD CONSTRAINT "ReceiptItem_receipt_id_fkey" FOREIGN KEY (receipt_id)
    REFERENCES public."Receipt" (receipt_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."ReceiptKeyword"
    ADD CONSTRAINT "ReceiptKeyword_receipt_id_fkey" FOREIGN KEY (receipt_id)
    REFERENCES public."Receipt" (receipt_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."ReceiptOCRField"
    ADD CONSTRAINT "ReceiptOCRField_receipt_id_fkey" FOREIGN KEY (receipt_id)
    REFERENCES public."Receipt" (receipt_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Reimbursement"
    ADD CONSTRAINT "Reimbursement_expense_id_fkey" FOREIGN KEY (expense_id)
    REFERENCES public."ExpenseRecord" (expense_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."Reimbursement"
    ADD CONSTRAINT "Reimbursement_status_id_fkey" FOREIGN KEY (status_id)
    REFERENCES public."GlobalReimbursementStatus" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."RevenueRecord"
    ADD CONSTRAINT "RevenueRecord_category_id_fkey" FOREIGN KEY (category_id)
    REFERENCES public."GlobalCategory" (category_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;


ALTER TABLE IF EXISTS public."RevenueRecord"
    ADD CONSTRAINT "RevenueRecord_source_id_fkey" FOREIGN KEY (source_id)
    REFERENCES public."GlobalSource" (source_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;

END;